FROM alpine:3.20

RUN apk add --no-cache openvpn easy-rsa dnsmasq iptables bash

COPY openvpn-entrypoint.sh /usr/local/bin/openvpn-entrypoint.sh
RUN chmod +x /usr/local/bin/openvpn-entrypoint.sh

EXPOSE 1194/udp

ENTRYPOINT ["/usr/local/bin/openvpn-entrypoint.sh"]
CMD ["server"]
