services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/etc:/etc/letsencrypt:ro
      - ./certbot/var:/var/lib/letsencrypt
      - ./certbot/webroot:/var/www/certbot:ro
      - ./nginx/webroot:/var/www/pr:ro
    depends_on:
      - n8n

  runner1:
    container_name: runner1
    restart: always
    image: public.ecr.aws/sam/build-provided.al2023:latest
    volumes:
      - ./nginx/webroot:/root/nginx
    working_dir: /root/actions-runner
    build:
      context: .
      dockerfile: Dockerfile.runner
      args:
        RUNNER_TOKEN: ACAM5B74RV4VUHLY3V6XTUDKF6S5Q
        LABELS: linux,arm64,asset

  runner2:
    container_name: runner2
    restart: always
    image: public.ecr.aws/sam/build-provided.al2023:latest
    volumes:
      - ./nginx/webroot:/root/nginx
    working_dir: /root/runner2
    build:
      context: .
      dockerfile: Dockerfile.runner
      args:
        RUNNER_NAME: runner2
        RUNNER_TOKEN: ACAM5B3ZOFH3QXCD3DHBIFDKF6THO
        LABELS: linux,arm64

  runner3:
    container_name: runner3
    restart: always
    image: public.ecr.aws/sam/build-provided.al2023:latest
    volumes:
      - ./nginx/webroot:/root/nginx
    working_dir: /root/runner3
    build:
      context: .
      dockerfile: Dockerfile.runner
      args:
        RUNNER_NAME: runner3
        RUNNER_TOKEN: ACAM5B2RJ5HYEZTKJR7QS5DKF6VJK
        LABELS: linux,arm64

  runner4:
    container_name: runner4
    restart: always
    image: public.ecr.aws/sam/build-provided.al2023:latest
    volumes:
      - ./nginx/webroot:/root/nginx
    working_dir: /root/runner4
    build:
      context: .
      dockerfile: Dockerfile.runner
      args:
        RUNNER_NAME: runner4
        RUNNER_TOKEN: ACAM5B3AAJVQH32IF6HM7FDKF7LE2
        LABELS: linux,arm64

  runner5:
    container_name: runner5
    restart: always
    image: public.ecr.aws/sam/build-provided.al2023:latest
    volumes:
      - ./nginx/webroot:/root/nginx
    working_dir: /root/runner5
    build:
      context: .
      dockerfile: Dockerfile.runner
      args:
        RUNNER_NAME: runner5
        RUNNER_TOKEN: ACAM5B6KK4MCYVY4RTYV7FLKF7LIM
        LABELS: linux,arm64

  runner6:
    container_name: runner6
    restart: always
    image: public.ecr.aws/sam/build-provided.al2023:latest
    volumes:
      - ./nginx/webroot:/root/nginx
    working_dir: /root/runner6
    build:
      context: .
      dockerfile: Dockerfile.runner
      args:
        RUNNER_NAME: runner6
        RUNNER_TOKEN: ACAM5BZEIN6JWOH7MS5UPIDKF7LLE
        LABELS: linux,arm64

  runner7:
    restart: always
    image: public.ecr.aws/sam/build-provided.al2023:latest
    volumes:
      - ./nginx/webroot:/root/nginx
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: runner7
    working_dir: /root/runner7
    build:
      context: .
      dockerfile: Dockerfile.runner
      args:
        RUNNER_NAME: runner7
        RUNNER_TOKEN: ACAM5B4QJVIEKMZU3W6U7VDKJXFEU
        LABELS: ubuntu,linux,arm64,docker

  runner8:
    restart: always
    image: public.ecr.aws/sam/build-provided.al2023:latest
    volumes:
      - ./nginx/webroot:/root/nginx
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: runner8
    working_dir: /root/runner8
    build:
      context: .
      dockerfile: Dockerfile.runner
      args:
        RUNNER_NAME: runner8
        RUNNER_TOKEN: ACAM5BYLY3JKVEZJ6QJWPBDKJXFMG
        LABELS: ubuntu,linux,arm64,docker

  runner9:
    restart: always
    image: public.ecr.aws/sam/build-provided.al2023:latest
    volumes:
      - ./nginx/webroot:/root/nginx
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: runner9
    working_dir: /root/runner9
    build:
      context: .
      dockerfile: Dockerfile.runner
      args:
        RUNNER_NAME: runner9
        RUNNER_TOKEN: ACAM5B57FIRZEMPKIUY4ZWDKJXFPC
        LABELS: ubuntu,linux,arm64,docker

  summer:
    container_name: summer
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.user
      args:
        USERNAME: summer
    environment:
      PORT: 18080
    volumes:
      - ./users/summer:/home/summer
      - /var/run/docker.sock:/var/run/docker.sock
      - ./summer-entrypoint.sh:/summer-entrypoint.sh
    working_dir: /home/summer/asset
    command: claude rc --name "Landing Wording UI" --permission-mode bypassPermissions

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./certbot/webroot:/var/www/certbot

  n8n:
    container_name: n8n
    restart: always
    image: docker.n8n.io/n8nio/n8n
    volumes:
      - ./.n8n:/home/node/.n8n
    environment:
      N8N_SECURE_COOKIE: false
      TZ: Asia/Seoul
      DB_TYPE: "sqlite"
      DB_SQLITE_DATABASE: "/home/node/.n8n/database.sqlite"
      N8N_PORT: "9000"
      EXECUTIONS_DATA_PRUNE: "true"
      EXECUTIONS_DATA_MAX_AGE: "168"
      GENERIC_TIMEZONE: "Asia/Seoul"
      N8N_DOMAIN: "n8n.hackartist.io"
      WEBHOOK_URL: https://n8n.hackartist.io/
      N8N_PROXY_HOPS: 1
      NODE_FUNCTION_ALLOW_BUILTIN: "*"
