FROM public.ecr.aws/sam/build-provided.al2023:latest


RUN cd /root && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > install.sh && \
    sh install.sh -y

RUN mkdir -p /usr/libexec/docker/cli-plugins/ && \
    curl -SL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-$(uname -m)" -o /usr/libexec/docker/cli-plugins/docker-compose && \
    chmod +x /usr/libexec/docker/cli-plugins/docker-compose

ENV PATH="/root/.cargo/bin:${PATH}"
ENV RUNNER_ALLOW_RUNASROOT=true
WORKDIR /root/runner

CMD ["/bin/bash", "-c", "/root/runner-entrypoint.sh"]
