mode: standalone
replicas: 1

rootUser: minioadmin
rootPassword: minioadmin

persistence:
  enabled: true
  storageClass: local-path
  size: 100Gi

nodeSelector:
  kubernetes.io/hostname: lima-k3s-server

resources:
  requests:
    memory: 512Mi

environment:
  MINIO_BROWSER_REDIRECT_URL: https://s3.miner.biyard.co

consoleIngress:
  enabled: true
  ingressClassName: nginx
  path: /
  hosts:
    - s3.miner.biyard.co
    - s3.dev.biyard.co
  tls:
    - secretName: miner-biyard-co-tls
      hosts:
        - s3.miner.biyard.co
    - secretName: dev-biyard-co-tls
      hosts:
        - s3.dev.biyard.co
