{{- range .Values.certs }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .dnsZone | replace "." "-" }}
spec:
  secretName: {{ .secretName }}
  dnsNames:
    - "*.{{ .dnsZone }}"
  issuerRef:
    name: letsencrypt-route53
    kind: ClusterIssuer
{{- end }}
